version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: es01
    ports:
      - 9200:9200
      - 9300:9300
    tty: true
    environment:
      discovery.type: single-node
    expose:
      - 9200
      - 9300
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.3.2
    container_name: kb01
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://localhost:9200

volumes:
  elasticsearch-data:
    driver: local